spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.133.1:8848
        namespace: 00a0082e-b0d6-4a45-964a-e865f9e69e49
      config:
        server-addr: 192.168.133.1:8848
        namespace: 00a0082e-b0d6-4a45-964a-e865f9e69e49
        group: DEFAULT_GROUP
        refresh-enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/user-service/**
#          filters:
#            - StripPrefix=1
  config:
    import: optional:nacos:gateway-server.yaml
  main:
    web-application-type: reactive
#    生产环境直接用代码加密密码，不用配置文件
#  security:
#    user:
#      name: admin
#      password: ${ACTUATOR_PASSWORD:Admin@123}
#      roles: ADMIN
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"              # 暴露所有端点（生产环境按需）
      base-path: /actuator        # 访问前缀
  endpoint:
    health:
      show-details: always        # 显示详细健康信息
    gateway:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
