spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务发现自动路由
    nacos:
      discovery:
        server-addr: 192.168.133.1:8848
  config:
    import: optional:nacos:${spring.cloud.nacos.discovery.server-addr}
    file-extension: yaml
    refresh-enabled: true
  main:
    web-application-type: reactive
server:
  port: 8080