spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.133.1:8848
        namespace: 00a0082e-b0d6-4a45-964a-e865f9e69e49
      config:
        server-addr: 192.168.133.1:8848
        namespace: 00a0082e-b0d6-4a45-964a-e865f9e69e49
        group: DEFAULT_GROUP
  config:
    import: optional:nacos:order-service.yml
server:
  port: 8082
powerjob:
  worker:
    app-name: test
    server-address: 192.168.133.1:7700  # PowerJob服务端地址
    protocol: http
    store-strategy: disk
    max-result-length: 4096
    max-lightweight-task-num: 4      # 最大同时运行的轻量级任务数
    max-heavyweight-task-num: 2      # 最大同时运行的重量级任务数
management:
  endpoints:
    web:
      exposure:
        include: "*"              # 暴露所有端点（生产环境按需）
      base-path: /actuator        # 访问前缀
  endpoint:
    health:
      show-details: always        # 显示详细健康信息
    gateway:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true